M48
; DRILL file {KiCad (6.0.10)} date Fri Jan  6 17:42:43 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-06T17:42:43-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X7.29Y-3.2611
X7.29Y-3.5289
T2
X3.795Y-3.865
X3.8Y-2.415
X7.215Y-3.865
T0
M30
